### ISSUE TITLE
[Question] Thoughts on "ansible_local" instead of custom script

### ISSUE THREAD

**Issue by garfieldcoked** [bertvv/ansible-skeleton#16]
Hi @bertvv, 

Thank you for an amazing project! I am currently reviewing and noticed that for Windows you are using a custom script because Ansible is not supported on a Windows hosts. I recently discovered that there is a [Ansible Local Provisioner](https://www.vagrantup.com/docs/provisioning/ansible_local.html) that you can use to run Ansible locally.

What are your thoughts on this? I know this project has been out for a while and might have been before the provisioner so I wanted to know if that was the reason or there is another factor that made you chose a custom script.

Again thank you for making this available.

**Comment by bertvv** [comment]
I used a custom script because at the time I created this project, `ansible_local` didn't exist and I wasn't yet aware that it existed.

Thank you for this suggestion, this would simplify the setup! I'll check it out.

**Comment by bertvv** [comment]
Implemented in 8f9bf63c35cfaf1afec134466cb960be691217f1!
