### ISSUE TITLE
Wrong version ansible installed

### ISSUE THREAD

**Issue by 642328ed** [bertvv/ansible-skeleton#19]
My host OS is windows, so I have to run ansible on the vm I am setting up. This gives me problems when setting up a fedora 24 client, because the version of ansible that gets installed is 2.2.0, which means that your other ansible roles don't fully work anymore

**Comment by T0MASD** [comment]
@642328ed I'm afraid you will need to upgrade fedora to at least 28, please see https://fedoramagazine.org/fedora-27-end-of-life/

**Comment by bertvv** [comment]
Agreed, Fedora versions are not supported beyond their end of life.
